### ISSUE TITLE
say hi to mom :)

### ISSUE THREAD

**Issue by ollibowers** [csesoc/Circles#1099]

**Comment by lhjt** [comment]
@ollibowers any updates?

**Comment by ollibowers** [comment]
update: I have booked a meeting with mom to discuss the requirements, hopefully will complete this task within the next week

**Comment by lhjt** [comment]
Thanks for the update. We look forward to progress and requirements.

**Comment by ollibowers** [comment]
I have now completed this task, will create further issues to represent the next steps!

**Comment by lhjt** [comment]
> I have now completed this task, will create further issues to represent the next steps!

Glad to hear! Good work; keen for the next objective 😎
