### ISSUE TITLE
Env file python script

### ISSUE THREAD

**Issue by ollibowers** [csesoc/Circles#1157]
Simple no dep python script built on dotenv or so, that sets up the env files. TUI. 

Required functionality:
- for env variables such as mongo password, where it lives in both backend env and mongodb env, you only need to input it in once
- if the files already exist, when the user is prompted to enter, suggests them to use the old one instead
  - this is because we dont want to accidently overwrite the files and be painful to find the auth env vars again
- certain fields allow for empty input, where it will auto generate
- also can specify as keyword command line arguments for easy use in the ci file
- otherwise if no CL argument or existing, will prompt user to enter each

Main usecases:
- in ci, replaces all the echos
- must leave files that are compatible with ci and docker compose env

`python3 setup_env.py --mongodb-pass="ollipass"`

**Comment by imagine-hussain** [comment]
Completed in #1159
