### ISSUE TITLE
Request: Allow Collapsing of Level X Core Courses

### ISSUE THREAD

**Issue by JamesTreloar** [csesoc/Circles#714]
When inputting core courses it is kind of annoying having to do a lot of scrolling past sections that are already fully inputted.
So minimising a section of things to select would be convenient.

A basic mockup with
| How it works now | How I want it to work |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/54793877/187366857-8f495ec7-4c61-4bf8-8a6a-a510262fa067.png) | ![image](https://user-images.githubusercontent.com/54793877/187366604-2957d593-8f36-4bdc-9060-3bf262c19b9f.png) |

**Comment by gtangelo** [comment]
Hi! Thank you for raising a feature request. Appreciate the feedback on the course menu and how we can improve the userflow. Raised a PR for this feature and it should be merged in soon~. 😄
