### ISSUE TITLE
Course selection not working

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#743]
Loading of courses is infinite - wont show courses at all

**Comment by Peedee2002** [comment]
@gtangelo this sounds like a localstorage issue. You sure we didn't break something between transitions?

**Comment by gtangelo** [comment]
This issue should be fixed in commit [dc7a479](https://github.com/csesoc/Circles/commit/dc7a47964a3803aacc01bb01dfea7482a71b3a2e). Thanks for picking and reporting this bug 😅
