### ISSUE TITLE
Gabriel is a very sexy male, he can 🍆  me anytime he wants

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#772]
every time i log onto Circles, the masculine image of Gabriel Ting rushes to my mind and it prevents me being able to plan my courses properly uwuwuwu 🥵

**Comment by gtangelo** [comment]
Hey, sorry that I'm preventing you to plan your courses 🥺. Unfortunately, I don't think I can do anything about that on my end hahaha. But ummm thanks alot? 😳👉👈
