### ISSUE TITLE
COMP3311 Term Offerings

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#821]
Circles is claiming that COMP3311 - Database Systems - is only offered during T1 of every year, despite the fact that I am currently enrolled in and participating in it in T3 2022. The handbook does indeed show that COMP3311 is offered in T1 and T3 every year.

**Comment by gtangelo** [comment]
@Peedee2002 may need to rerun the scrappers sometime soon?

**Comment by Peedee2002** [comment]
Nope this is a legacy bug. Plz implement legacy fetching 🙏

**Comment by gtangelo** [comment]
I think the handbook got updated after you ran the scappers tho? Like 3311 nows shows its offerred in T1 and T3.

https://www.handbook.unsw.edu.au/undergraduate/courses/2023/COMP3311/

Also, with some other courses like COMP6771 and COMP6841, the handbook got updated to show the new terms for 2023 whilst we currrently don't have that data?

**Comment by Peedee2002** [comment]
oop yup fixed this
