### ISSUE TITLE
Error when returning to the course selector page 

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#826]
This probably isn't the most helpful bug description but I clicked the course selector button on the navbar while on the planner page and the following errors showed up:

Error
{"fileName":"","lineNumber":0,"columnNumber":0,"message":"error loading dynamically imported module"}

Error Info
w1@https://circles.csesoc.app/assets/vendor.31446e91.js:89:4392 lS@https://circles.csesoc.app/assets/vendor.31446e91.js:89:6403 P1@https://circles.csesoc.app/assets/vendor.31446e91.js:89:5908 uS@https://circles.csesoc.app/assets/vendor.31446e91.js:98:427 u@https://circles.csesoc.app/assets/index.7e7b94de.js:8:73 Suspense cS@https://circles.csesoc.app/assets/vendor.31446e91.js:101:5051 $e@https://circles.csesoc.app/assets/index.56b1353c.js:53:4029 t@https://circles.csesoc.app/assets/vendor.31446e91.js:71:15167 eS@https://circles.csesoc.app/assets/vendor.31446e91.js:71:822

Not sure if google forms will keep the whitespace in, so my apologies if the formatting is a bit off. Thanks for all the hard work on the site you guys!

**Comment by Peedee2002** [comment]
Bruh plz someone just force a reload if the error boundary catches this error ty
